const config = {
  "IMAGE_PATH": "https://images.shunyape.com",
  "TOKEN_KEY": "khateraho",
  "PROTOCOL": "http",
  "HOST": "localhost",
  "PORT": 3001,
  "SMS_URL": "https://api.textlocal.in/send/",
  "SMS_API_KEY": "NmM0ZjRkNDQzMDc4NGI3YTY1NDQzNDZiNGE1YTUzNzE=",
  "SENDER": "IWCNKR",
  "kr_support_email": "support@khateraho.com",
  "qordernumber": 101,
  "currency_symbol": "₹",
  "kotnumber": 1,
  "IMAGE_PATH_SERVER_ROOT": "/home/shunyape/images.shunyape.com",
  "NO_IMAGE_PATH": "https://images.shunyape.com/img/noimage.png",
  "USER_EMAIL": "support@khateraho.com",
  "USER_EMAIL_PASS": "Agra2025!",
  "qrcode_base_url": "https://shunyape.com",
  "encrypt_method": "aes-256-cbc",
  "secret_key": "iwcn",
  "secret_iv": "7895215780",
  "reset_link": "https://fooders.shunyape.com/reset_password",
  "image_directory": "images.shunyape.com",
  "mp": "Batman2024!",
  "max_area_coverage": 20,
  "invoice_number_prefix": "Bill No.",
  "whatsapp_massageing_api_base_URL": "https://vayureach.com/api",
  "razorpay_key_id": "rzp_live_l3PLTMuk8Qvm90",
  "razorpay_key_secret": "068iMHZCcssj7lANXsiAeuYQ",
  "whatsapp_massageing_campen_URL": "https://vayureach.com/api/c9479ed9-11b2-4b30-83e7-8c77dedc7ba6/contact/send-template-message",
  "whatsapp_massageing_campen_Token": "IHlgpnIRbO074tivfBVynec7bleaZRejOmM4tkihNwwETIbOjsdN8WwBukVJOVi9",
  "whatsapp_massageing_campen_template_name": "update_order_status",
  "whatsapp_otp_template_name": "otp",
  "whatsapp_massageing_whatsapp_vendor_uid": "c9479ed9-11b2-4b30-83e7-8c77dedc7ba6",
  "display_system_price":1999,
  "whatsapp_marketing_price":3499,
  "kds_price":2999,
  "email_whatsapp_massageing_campen_URL": "https://hook.us2.make.com/3mvybcaxtxcvqczsyvhdm9e6vs9k6wwl",
  "alertifyenvironment": "devnode_",
  "lastorderid": 10819,
};

module.exports = config;